# Generated by Django 4.2 on 2023-04-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommend", "0013_auto_20200611_2207"),
    ]

    operations = [
        migrations.AddField(
            model_name="myrating",
            name="genre",
            field=models.CharField(default="Pop", max_length=100),
        ),
    ]
