# Generated by Django 4.2 on 2023-04-23 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recommend", "0014_myrating_genre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myrating",
            name="genre",
        ),
    ]
