# Generated by Django 4.2 on 2023-05-10 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recommend", "0015_remove_myrating_genre"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Movie",
            new_name="Song",
        ),
    ]
