# Generated by Django 4.2 on 2023-05-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recommend", "0016_rename_movie_song"),
    ]

    operations = [
        migrations.RenameField(
            model_name="song",
            old_name="movie_logo",
            new_name="song_logo",
        ),
    ]
